name: Feature Request
description: Propose a new feature for eloquent-wherelike package
title: "[Feature Request]: "
labels: [feature request]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing a feature for eloquent-wherelike package.
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: How should this feature look like?
      placeholder: Location in the software, usage, output ...
    validations:
      required: true
  - type: textarea
    id: valuable
    attributes:
      label: Is this feature valuable for other users as well and why?
      